/** Nakshatra icon paths — maps slug to WebP asset */
export const NAKSHATRA_ICONS: Record<string, string> = {
  ashvini: "/assets/jyotish/nakshatras/ashvini.webp",
  bharani: "/assets/jyotish/nakshatras/bharani.webp",
  krittika: "/assets/jyotish/nakshatras/krittika.webp",
  rohini: "/assets/jyotish/nakshatras/rohini.webp",
  mrigashira: "/assets/jyotish/nakshatras/mrigashira.webp",
  ardra: "/assets/jyotish/nakshatras/ardra.webp",
  punarvasu: "/assets/jyotish/nakshatras/punarvasu.webp",
  pushya: "/assets/jyotish/nakshatras/pushya.webp",
  ashlesha: "/assets/jyotish/nakshatras/ashlesha.webp",
  magha: "/assets/jyotish/nakshatras/magha.webp",
  "purva-phalguni": "/assets/jyotish/nakshatras/purva-phalguni.webp",
  "uttara-phalguni": "/assets/jyotish/nakshatras/uttara-phalguni.webp",
  hasta: "/assets/jyotish/nakshatras/hasta.webp",
  chitra: "/assets/jyotish/nakshatras/chitra.webp",
  swati: "/assets/jyotish/nakshatras/swati.webp",
  vishakha: "/assets/jyotish/nakshatras/vishakha.webp",
  anuradha: "/assets/jyotish/nakshatras/anuradha.webp",
  jyeshtha: "/assets/jyotish/nakshatras/jyeshtha.webp",
  mula: "/assets/jyotish/nakshatras/mula.webp",
  "purva-ashadha": "/assets/jyotish/nakshatras/purva-ashadha.webp",
  "uttara-ashadha": "/assets/jyotish/nakshatras/uttara-ashadha.webp",
  shravana: "/assets/jyotish/nakshatras/shravana.webp",
  dhanishtha: "/assets/jyotish/nakshatras/dhanishtha.webp",
  shatabhisha: "/assets/jyotish/nakshatras/shatabhisha.webp",
  "purva-bhadrapada": "/assets/jyotish/nakshatras/purva-bhadrapada.webp",
  "uttara-bhadrapada": "/assets/jyotish/nakshatras/uttara-bhadrapada.webp",
  revati: "/assets/jyotish/nakshatras/revati.webp",
};
